export const testDate = {
    data: {
        Articles: [
            {
                __typename: 'Article',
                id: 29,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 25,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 24,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 23,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 19,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 18,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 17,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 15,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 14,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 13,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 1,
                title: 'sample',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '러블',
                    gender: '남',
                    foundDate: '2021-10-03T01:47:09.549Z',
                    feature: '개냥이',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 1,
                title: 'sample',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '러블',
                    gender: '남',
                    foundDate: '2021-10-03T01:47:09.549Z',
                    feature: '개냥이',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 29,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 25,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 24,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 23,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 19,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 18,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 17,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 15,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 14,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 13,
                title: 'asd',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '123',
                    gender: '123',
                    foundDate: '2020-12-11T15:00:00.000Z',
                    feature: '123',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 1,
                title: 'sample',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '러블',
                    gender: '남',
                    foundDate: '2021-10-03T01:47:09.549Z',
                    feature: '개냥이',
                    location: {
                        a: null,
                    },
                },
            },
            {
                __typename: 'Article',
                id: 1,
                title: 'sample',
                content: 'content',
                articleDetail: {
                    __typename: 'LFG',
                    breed: '러시안 블루',
                    name: '러블',
                    gender: '남',
                    foundDate: '2021-10-03T01:47:09.549Z',
                    feature: '개냥이',
                    location: {
                        a: null,
                    },
                },
            },
        ],
    },
};
